### PR TITLE
build system, syntax test and space after  `.`

### PR DESCRIPTION
**Pull request by stoivo**
Minor improvments

### CODE REVIEW

**Comment by ngraymon** [comment]
Seems fine on a quick glance, I'll try to run the build system tomorrow and see how the tests look. I haven't used the testing system so it should be a good learning experience for me.

**Comment by stoivo** [comment]
When a syntax files become bigger the harder it is to remember all cases so I relly like to have syntax tests. Here are the docs https://www.sublimetext.com/docs/syntax.html#testing

**Comment by ngraymon** [comment]
Seems 5 of the tests are failing for me?
I haven't used the testing system before, possibly I'm not using it correctly.

1. I checked out a local branch of `st-fixes` 
2. copied the three files `maude.sublime-build` `maude.sublime-syntax` and `syntax_test_module.maude` into my
`C:\Users\$USER\AppData\Roaming\Sublime Text 3\Packages\User` directory 
3. open `syntax_test_module.maude` in SublimeText
4. Tools -> Run Build 

Output
```
Packages/User/syntax_test_module.maude:8:21: [- keyword.operator] does not match scope [source.maude keyword.operator.maude]
Packages/User/syntax_test_module.maude:8:22: [- keyword.operator] does not match scope [source.maude keyword.operator.maude]
Packages/User/syntax_test_module.maude:8:23: [- keyword.operator] does not match scope [source.maude keyword.operator.maude]
Packages/User/syntax_test_module.maude:26:18: [keyword.operator.maude] does not match scope [source.maude keyword.operator.logical.maude]
Packages/User/syntax_test_module.maude:26:27: [- keyword.operator] does not match scope [source.maude keyword.operator.maude]
FAILED: 5 of 53 assertions in 1 files failed
[Finished]
```

If I create a local branch from `stoivo` and repeat the process it seems that some asserts fail for each of the three build files.

**Comment by stoivo** [comment]
It works for me. You have to remove the existing file too, maybe. We could try to fix it together. I like to pair with tuple.app. I sent you an invite link by email.

**Comment by ngraymon** [comment]
I'm working on windows 10 through WSL2.
Seems tuple.app doesn't work for linux yet so I won't be able to use it?
For sharing screen zoom or teams are options for me.

**Comment by ngraymon** [comment]
First check, does the order of operations I described have any issues?
I can try and build again now and see if there is a difference.

**Comment by ngraymon** [comment]
If I am on de5e84fd398c71e65af828e0f8e4f05583fe975e specifically and I run the build then the first error is 
> Packages/User/syntax_test_one.maude:8:9: [entity.name.function.maude] does not match scope [source.maude]

referring to this section
```
    rl [separsationInit] :
*** ^ keyword.control.statements.maude
***     ^^^^^^^^^^^^^^^ entity.name.function.maude
***                      ^ keyword.operator.maude
```

Which in `maude.sublime_syntax` is defined as
```
  rule_label:
    - meta_content_scope: entity.name.function.maude
    - match: ([A-Za-z0-9-_!&^@#$%*']*)
    - match: \]
      pop: true
    - match: .
      scope: invalid.illegal
```

and then is used in 
```
  entity:
    - match: (rl|crl)
      scope: keyword.control.statements.maude
    - match: \[
      push: rule_label
```

Is the issue that the file ending is `.maude` and so there is some circular reference?
Or is the problem that the `entity` definition doesn't have a connection to the `source.maude` scope?

**Comment by stoivo** [comment]
Too bad, Tuple is realy greate. Currently Osx only. We can use https://meet.jit.si/sublime-maude

**Pull request merged**
