### PR TITLE
Improve syntax for comment and enable toggling

### PR DESCRIPTION
**Pull request by stoivo**
Not realy sure what didn't work woth block comments for you, @ngraymon, but it seams to work fine now

### CODE REVIEW

**Comment by ngraymon** [comment]
Per the maude manual multiline comments can be delimited by `***(` and `)` page_39_of_615

However I was not able to get that to work when the contents of the selection included a `)`. The implementation that I wrote comments a multi line selection as multiple single line comments... which works well enough, but isn't "perfect".

That is why I had the `TM_COMMENT_START_3` section commented out in Comments.tmPreferences. 

You're saying with the changes from c8dca768e2011be0db776bf089b33a4f80121458 that it now works when the multi line selection has `)` and `(` characters inside of it?

**Comment by stoivo** [comment]
I tried to leave a comment in the syntax file itself. Both --- and *** can be used as block comments by the interperator so I whith we can hightlight it like that too. Worst care it that we teach folks to use ---() but and it gets removed from a language. Also it seam like you can have space between --- and the first `(` and still be a new line.
```
Maude> ---(comment) red 1 + 1 .                                                                                             
reduce in CONVERSION : 1 + 1 .
rewrites: 1 in 0ms cpu (0ms real) (100000 rewrites/second)
result NzNat: 2
Maude> ***(comment) red 1 + 1 .                                                                                             
reduce in CONVERSION : 1 + 1 .
rewrites: 1 in 0ms cpu (0ms real) (1000000 rewrites/second)
result NzNat: 2
Maude> --- line (comment) red 1 + 1 .                                                                                       
> --- line (comment) red 1 + 1 .                                                                                            
> *** line (comment) red 1 + 1 .                                                                                             
reduce in CONVERSION : 1 + 1 .
rewrites: 1 in 0ms cpu (0ms real) (~ rewrites/second)
result NzNat: 2
```

> However I was not able to get that to work when the contents of the selection included a `)`

example?

The block commets works fine when I have a selection.

> You're saying with the changes from [c8dca76](https://github.com/sublime-maude/maude_syntax_highlight/commit/c8dca768e2011be0db776bf089b33a4f80121458) that it now works when the multi line selection has `)` and `(` characters inside of it?

If you have loose, dangelig close `)`, of course it want work.  You can comment out  `(search ....)`

**Comment by stoivo** [comment]
Might have something do to with the new parsing off comments the previous implementation required  ending`)` to be on a new line.

**Comment by ngraymon** [comment]
I saw you did some more pushes, did you still want to continue with this branch?
I am happy to merge but I will wait until you confirm.

**Comment by stoivo** [comment]
Can't image any more bugs related to comments so I will merge

**Pull request merged**
